config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks",
                           registrations: "registrations"}
  scope "(:locale)", locale: /en|vi/ do
    mount Api::Base, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/documentation"
    require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
    root "home_pages#index"
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registration#new"
    end
    delete "/carts", to: "carts#destroy"
    put "/carts", to: "carts#update_quantity"
    resources :home_pages, only: %i(index show)
    namespace :admin do
      root "books#index"
      resources :books do
        member do
          get :restore
        end
      end
      resources :charts, only: :index
      resources :orders, only: %i(index update show)
    end
    resources :home_pages, only: :index
    resources :books
    resources :orders
    resources :carts, only: %i(index create)
  end
end

app/models/book.rb
class Book < ApplicationRecord
  BOOK_ATTRS = %i(name description price publish_year publisher_id
    category_id image).push(book_details_attributes: [:id, :edition, :quantity,
    :_destroy]).push(author_ids: []).freeze
  belongs_to :category
  belongs_to :publisher
  has_many :book_details, dependent: :destroy
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many :rates, dependent: :destroy
  has_many :users, through: :rates
  has_one_attached :image
  delegate :name, to: :category, prefix: true, allow_nil: true
  delegate :name, to: :publisher, prefix: true, allow_nil: true

  validates :name, presence: true, uniqueness: true,
            length: {maximum: Settings.max_name_book_length}
  validates :price, presence: true,
            format: {with: Settings.format_price},
            numericality: {greater_than: Settings.min_book_price_length,
                           less_than: Settings.max_book_price_length}
  validates :description, presence: true,
            length: {maximum: Settings.max_description_length}
  validates :image,
            content_type: {in: Settings.image_format,
                           message: I18n.t("invalid_format")},
            size: {less_than: Settings.image_size.megabytes,
                   message: I18n.t("invalid_size")}
  validates :category_id, presence: true
  validates :publisher_id, presence: true
  accepts_nested_attributes_for :book_details, :book_authors,
                                allow_destroy: true
  scope :newest, ->{order(created_at: :desc)}

  scope :search,
        ->(search){where("name LIKE ?", "%#{search}%") if search.present?}

  acts_as_paranoid

  def dollar_to_vnd
    price * Settings.dollar_to_vnd if price.present?
  end

  def display_image
    image.variant resize_to_limit: Settings.image_limit
  end

  ransacker :created_at, type: :date do
    Arel.sql("date(created_at)")
  end

  class << self
    def dollar_to_vnds books
      books.map(&:dollar_to_vnd)
    end

    def ransackable_attributes _auth_object = nil
      super %w(created_at) + _ransackers.keys
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::AdminController
  before_action :load_book_info, except: %i(index destroy)
  before_action :load_book, only: %i(update edit destroy)
  authorize_resource

  def index
    @products = Book.with_deleted.search(params[:admin_search]).newest
    @pagy, @new_products = pagy @products, items: Settings.page_items
    return @prices = @new_products.pluck(:price) unless is_vi_location?

    @prices = Book.dollar_to_vnds(@new_products)
  end

  def new
    @book = Book.new
    @book.book_details.build
    @book.book_authors.build
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t ".success"
      redirect_to admin_books_path
    else
      flash.now[:danger] = t ".error"
      render :new
    end
  end

  def edit; end

  def update
    if @book.update book_params
      flash[:success] = t "update_book_success"
      redirect_to admin_root_path
    else
      flash.now[:danger] = t "update_book_fail"
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @book.destroy
        format.js{flash.now[:notice] = t ".book_deleted"}
      else
        format.js{flash.now[:danger] = t ".delete_fail"}
      end
    end
  end

  def restore
    @book = Book.with_deleted.find_by(id: params[:id])
    respond_to do |format|
      if @book&.restore(recursive: true)
        format.js{flash.now[:notice] = t ".book_restored"}
      else
        format.js{flash.now[:danger] = t ".restore_fail"}
      end
    end
  end

  private
  def load_book
    @book = Book.find_by(id: params[:id])
    return if @book

    flash.now[:danger] = t "book_not_found"
    render :index
  end

  def book_params
    params.require(:book)
          .permit(Book::BOOK_ATTRS)
  end

  def load_book_info
    @category = Category.pluck(:name, :id)
    @publishers = Publisher.pluck(:name, :id)
    @authors = Author.pluck(:name, :id)
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td><%= books.index(book) + 1 %></td>
  <td><%= book.id %></td>
  <td><%= book.category_name %></td>
  <td><%= book.publisher_name %></td>
  <td><%= book.name %></td>
  <td><%= image_tag book.display_image if book.image.attached? %></td>
  <td>
    <ul>
      <li>
        <%= t "description_book" %>
      </li>
      <ul>
        <li>
          <%= book.description %>
        </li>
      </ul>
    </ul>
    <ul>
      <li>
        <%= t "author_book" %>
      </li>
      <ul>
        <% if book.book_authors.present? %>
          <% book.book_authors.each do |at| %>
            <li>
              <%= at.author_name %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </ul>
  </td>
  <td><%= number_to_currency(prices[book_iteration.index]) %></td>
  <td>
    <% if book.deleted_at.nil? %>
      <%= link_to edit_admin_book_path(book) do %>
        <label class="btn btn-warning">
          <i class="fa-solid fa-pen-to-square"></i>
        </label>
      <% end %>
      <%= link_to admin_book_path(book),method: :delete,
                                        data: {confirm: t("delete_book?")},
                                        remote: true,
                                        class: "book_delete" do %>
        <label class="btn btn-danger">
          <i class="fa-solid fa-trash-can"></i>
        </label>
      <% end %>
    <% else %>
      <%= link_to restore_admin_book_path(book), class: "book_restore", remote: true do %>
        <label class="btn btn-warning">
          <i class="fa-solid fa-recycle"></i>
        </label>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/books/_book_detail_fields.html.erb
<div class="nested-fields row g-3">
  <div class="col-md-6 required">
    <%= f.label :edition, t("edition") %>
    <%= f.text_field :edition,
          {class: "form-control", placeholder: t("input_edition")} %>
    <%= errors_for f, :edition %>
  </div>
  <div class="col-md-5 required">
    <%= f.label :quantity, t("quantity") %>
    <%= f.number_field :quantity,
          {class: "form-control",
          placeholder: t("input_quantity"),
          min: Settings.min_val} %>
    <%= errors_for f, :quantity %>
  </div>
  <div class="links col-md-1">
    <label><%= t "action" %></label>
    <%= link_to_remove_association f do %>
      <label class="btn btn-danger form-control">
        <i class="fa-solid fa-trash-can"></i>
      </label>
    <% end %>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {class: "row g-3"} do |f| %>
  <div class="col-md-6 required">
    <%= f.label :name, t("input_name_label") %>
    <%= f.text_field :name,
        {class: "form-control", placeholder: t("input_name")} %>
    <%= errors_for f, :name %>
  </div>
  <div class="col-md-6 required">
    <%= f.label :price, t("input_price_label") %>
    <%= f.number_field :price,
        {class: "form-control",
         placeholder: t("input_price"),
         min: Settings.min_book_price_length,
         max: Settings.max_book_price_length} %>
    <%= errors_for f, :price %>
  </div>
  <div class="col-md-6 required">
    <%= f.label :category_id, t("category") %>
    <%= f.select :category_id,
        options_for_select(@category, selected_category(@book)),
                          {},
                          {class: "form form-control"} %>
    <%= errors_for f, :category_id %>
  </div>
  <div class="col-md-6 required">
    <%= f.label :publisher_id, t("publisher") %>
    <%= f.select :publisher_id,
        options_for_select(@publishers, selected_publisher(@book)),
                          {},
                          {class: "form form-control"} %>
    <%= errors_for f, :publisher_id %>
  </div>
  <div class="row g-3">
    <%= f.fields_for :book_details do |ff| %>
      <%= render partial: "book_detail_fields", locals: {f: ff} %>
    <% end %>
    <div class="col-md-12">
      <%= link_to_add_association f, :book_details do %>
        <label class="btn btn-outline-primary">
          <i class="fas fa-folder-plus"></i>
          <%= t ".add_book_detail" %>
        </label>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <%= f.label :publish_year, t("publish_year") %>
    <%= f.date_field :publish_year, {class: "form-control"} %>
  </div>
  <div class="col-md-6 required">
    <%= f.label :book_authors, t("book_authors") %>
    <%= f.select :author_ids,
        options_for_select(@authors, selected_book_authors(@book)),
                           {include_blank: true},
                           multiple: true,
                           class: "form-control select2" %>
    <%= errors_for f, :book_authors %>
  </div>
  <div class="col-md-12 required">
    <%= f.label :description, t("description") %>
    <%= f.text_area :description, {class: "form-control",
                                   placeholder: t("input_description")} %>
    <%= errors_for f, :description %>
  </div>
  <div class="col-md-12 row g-3">
    <div class="col-sm-8">
      <%= f.label :image, t("image") %>
      <%= f.file_field :image,
          {accept: Settings.image_formats,
          class: "form-control", placeholder: t("input_image")} %>
    </div>
    <div class="col-sm-4">
      <% if @book.image.attached? %>
        <%= image_tag @book.display_image %>
      <% end %>
    </div>
  </div>
  <div class="col-12">
    <%= f.submit yield(:button_text), class: "btn btn-primary mt-5" %>
  </div>
<% end %>

app/views/admin/books/destroy.js.erb
$('.book_delete').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
  toastr['info']("<%= notice %>");
});

app/views/admin/books/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t("update_book") %>
<h1 class="h3 mb-2 text-gray-800">
  <%= t ".edit_book" %>
</h1>

<div class="card shadow mb-4">
  <div class="card-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t(".books") %>
<h1 class="h3 mb-2 text-gray-800">
  <%= t ".books" %> |
  <%= link_to new_admin_book_path do %>
    <label class="btn btn-outline-primary">
      <i class="fas fa-folder-plus"></i>
      <%= t ".add_book" %>
    </label>
  <% end %>
</h1>
<p class="mb-4">
  <%= t ".book_list" %> |
  <%= t ".book_count" %> : <span><%= @products.count %> </span>
</p>
<div class="card shadow mb-4">
  <div class="card-body">
    <%== pagy_bootstrap_nav(@pagy) %>
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th><%= t "index" %></th>
            <th><%= t ".book_id" %></th>
            <th><%= t "category" %></th>
            <th><%= t "publisher" %></th>
            <th><%= t ".name" %></th>
            <th><%= t ".image" %></th>
            <th><%= t ".description" %></th>
            <th><%= t ".price" %></th>
            <th><%= t ".edit" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @new_products, prices: @prices, books: @products %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/books/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t("create_new_book") %>
<h1 class="h3 mb-2 text-gray-800">
  <%= t ".add_new_book" %>
</h1>

<div class="card shadow mb-4">
  <div class="card-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/restore.js.erb
$('.book_restore').bind('ajax:success', function() {
  $(this).closest('tr').fadeOut();
  toastr['info']("<%= notice %>");
});