config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks",
                           registrations: "registrations"}
  scope "(:locale)", locale: /en|vi/ do
    mount Api::Base, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/documentation"
    require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
    root "home_pages#index"
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registration#new"
    end
    delete "/carts", to: "carts#destroy"
    put "/carts", to: "carts#update_quantity"
    resources :home_pages, only: %i(index show)
    namespace :admin do
      root "books#index"
      resources :books do
        member do
          get :restore
        end
      end
      resources :charts, only: :index
      resources :orders, only: %i(index update show)
    end
    resources :home_pages, only: :index
    resources :books
    resources :orders
    resources :carts, only: %i(index create)
  end
end

app/views/admin/layouts/_footer.html.erb
<section class="info_section ">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="info_contact">
          <h5>
            <a href="" class="navbar-brand">
              <span>
                <%= t ".bookstore" %>
              </span>
            </a>
          </h5>
          <p>
            <i class="fa fa-map-marker" aria-hidden="true"></i>
              <%= t ".address" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/layouts/_header.html.erb
<div class="hero_area">
  <header class="header_section">
    <div class="header_top">
      <div class="container-fluid">
        <div class="top_nav_container">
         <%= link_to t(".bookstore"), home_pages_path, class: "navbar-brand" %>
          <%= form_tag(home_pages_path, method: :get, class: "search_form") do %>
            <%= text_field_tag :search, params[:search],
                                        class: "form-control",
                                        placeholder: t("search") %>
            <%= button_tag(type: "submit", class: "btn btn-default") do %>
              <i class="fa fa-search"></i>
            <% end %>
          <% end %>
          <div class="user_option_box">
            <span><%= link_to t("vi"), locale: :vi %></span>
            <span><%= link_to t("en"), locale: :en %></span>
            <% if logged_in? %>
              <a href="" class="account-link">
              <i class="fa fa-user" aria-hidden="true"></i>
              <span>
                 <%= link_to t(".logout"), logout_path, method: :delete %>
              </span>
            </a>
            <% else %>
              <span>
                 <%= link_to t(".login"), login_path %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </header>
</div>

app/views/admin/layouts/_left.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <%= link_to t("dashboard"), admin_root_path,
      class: "sidebar-brand d-flex align-items-center justify-content-center"
  %>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to admin_orders_path, class: "nav-link collapsed" do %>
      <i class="fas fa-fw fa-cog"></i>
      <span><%= t ".orders" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to admin_books_path, class: "nav-link collapsed" do %>
      <i class="fas fa-fw fa-folder"></i>
      <span><%= t ".products" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to admin_charts_path, class: "nav-link collapsed" do %>
      <i class="fa-solid fa-chart-line"></i>
      <span><%= t ".analyst" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <div class = "nav-link collapsed">
      <i class="fa-solid fa-language"></i>
      <%= link_to t("vi"), locale: :vi, class: "vi_en_white" %> |
      <%= link_to t("en"), locale: :en %>
    </div>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to home_pages_path, class: "nav-link collapsed" do %>
      <i class="fa-solid fa-house"></i>
      <span><%= t ".bookstore" %></span>
    <% end %>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <%= link_to logout_path, method: :delete, class: "nav-link collapsed" do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
      <span><%= t ".logout" %></span>
    <% end %>
  </li>
</ul>

app/views/admin/layouts/_right.html.erb
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
      <%= form_tag(admin_books_path, method: :get, class: "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search") do %>
        <%= text_field_tag :admin_search, params[:admin_search],
                                          class: "form-control bg-light border-0 small",
                                          placeholder: t("search") %>
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="fas fa-search fa-sm"></i>
        <% end %>
      <% end %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow d-sm-none">
          <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
          </a>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>
      </ul>
    </nav>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= toastr_flash %>
      <%= yield %>
    </div>
  </div>
</div>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="images/fevicon.png" type="image/gif"/>
  </head>

  <body>
    <div id="wrapper">
      <%= render "admin/layouts/left" %>
      <%= render "admin/layouts/right" %>
    </div>
    <%= render "admin/layouts/footer" %>
  </body>
</html>