config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks",
                           registrations: "registrations"}
  scope "(:locale)", locale: /en|vi/ do
    mount Api::Base, at: "/"
    mount GrapeSwaggerRails::Engine, at: "/documentation"
    require "sidekiq/web"
      mount Sidekiq::Web => "/sidekiq"
    root "home_pages#index"
    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registration#new"
    end
    delete "/carts", to: "carts#destroy"
    put "/carts", to: "carts#update_quantity"
    resources :home_pages, only: %i(index show)
    namespace :admin do
      root "books#index"
      resources :books do
        member do
          get :restore
        end
      end
      resources :charts, only: :index
      resources :orders, only: %i(index update show)
    end
    resources :home_pages, only: :index
    resources :books
    resources :orders
    resources :carts, only: %i(index create)
  end
end

app/views/layouts/_header.html.erb
<div class="hero_area">
  <header class="header_section">
    <div class="header_top">
      <div class="container-fluid">
        <div class="top_nav_container">
          <%= search_form_for @q, url: home_pages_path, class: "search_form" do |f| %>
            <%= f.search_field :description_or_name_cont, class: "form-control",
                                           placeholder: t("search") %>
            <%= f.submit t("button_search"), {class: "btn btn-primary"} %>
          <% end %>
          <div class="user_option_box">
            <span><%= link_to t("vi"), locale: :vi %></span>
            <span><%= link_to t("en"), locale: :en %></span>
            <% if user_signed_in? %>
              <a href="" class="account-link">
              <i class="fa fa-user" aria-hidden="true"></i>
              <span>
                 <%= link_to t(".logout"), logout_path, method: :delete %>
              </span>
            </a>
            <a href="" class="cart-link">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
              <span>
                <%= link_to t(".cart"), carts_path %>
              </span>
              <span>
                <%= link_to t(".orders"), orders_path %>
              </span>
            </a>
            <% else %>
              <span>
                 <%= link_to t(".login"), new_user_session_path %>
              </span>
              <span>
                 <%= link_to t(".signup"), new_user_registration_path %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="header_bottom">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <%= link_to t(".bookstore"), home_pages_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <%= link_to t("home"), home_pages_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to t(".admin"), admin_books_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <title><%= full_title yield(:title) %></title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="images/fevicon.png" type="image/gif"/>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= toastr_flash %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>